[package]
name = "osrepo"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.24"
dirs = "4.0.0"
serde = { version = "1.0.137", features = ["derive"] }
